### ISSUE TITLE
IF auto-download not working

### ISSUE THREAD

**Issue by ambocclusion** [Zuellni/ComfyUI-Custom-Nodes#4]
I'm having some issues with the nodes downloading the required models in Windows. This is the error I get:

`Error occurred when executing Zuellni IF Load Stage I:

[Errno 2] No such file or directory: 'C:\\Users\\XXXXXX\\.cache\\huggingface\\hub\\models--DeepFloyd--IF-I-XL-v1.0\\refs\\main'

  File "E:\AI\stable diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Nodes\Nodes\IF.py", line 115, in process
    model = DiffusionPipeline.from_pretrained(
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 882, in from_pretrained
    cached_folder = cls.download(
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1324, in download
    cached_folder = snapshot_download(
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\AI\stable diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:`

I'm not sure what method I could use to manually download the model to the Users location, the manual copies I've tried haven't worked.

**Comment by Zuellni** [comment]
This appears to be an issue with the portable version of ComfyUI, I can't reproduce it in any way currently though.

**Comment by EricRollei** [comment]
I've got the Windows portable and it's downloading the files but there are some errors 
here's the console log from downloading the stage II files. It started automatically for me, and same with the stage III files.  It looks like there are some files which didn't get downloaded.   My worflow with IF Stage III runs but it doesn't make a sharp image really so I'm wondering if that's because of the missing files.  I wish I had saved the console log from that one.  


Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 692/692 [00:00<?, ?B/s]
unet\diffusion_pytorch_model.fp16.safetensors not found

A mixture of fp16 and non-fp16 filenames will be loaded.
Loaded fp16 filenames:
[text_encoder/pytorch_model.fp16-00002-of-00002.bin, safety_checker/pytorch_model.fp16.bin, unet/diffusion_pytorch_model.fp16.bin, text_encoder/pytorch_model.fp16-00001-of-00002.bin]
Loaded non-fp16 filenames:
[watermarker/diffusion_pytorch_model.bin
If this behavior is not expected, please check your folder structure.
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 2.20MB/s]
Downloading (…)901/unet/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████| 1.72k/1.72k [00:00<00:00, 3.43MB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2.50k/2.50k [00:00<00:00, 2.49MB/s]
Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 454/454 [00:00<00:00, 303kB/s]
Downloading (…)_checker/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████| 4.92k/4.92k [00:00<00:00, 9.83MB/s]
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 424/424 [00:00<?, ?B/s]
Downloading (…)_encoder/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 741/741 [00:00<?, ?B/s]
Downloading (…)ermarker/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 74.0/74.0 [00:00<?, ?B/s]
Downloading spiece.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:00<00:00, 2.36MB/s]
Downloading (…)torch_model.fp16.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2.49G/2.49G [06:44<00:00, 6.15MB/s]
Fetching 11 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [06:45<00:00, 36.87s/it]
Loading pipeline components...:   0%|                                                                                                            | 0/4 [00:00<?, ?it/s]You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.76it/s]
Pipelines loaded with `torch_dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Downloading (…)_encoder/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 741/741 [00:00<?, ?B/s]
Downloading (…)sors.index.fp16.json: 100%|████████████████████████████████████████████████████████████████████████████████████████| 21.0k/21.0k [00:00<00:00, 1.91MB/s]
Downloading shards:   0%|                                                                                                                        | 0/2 [00:00<?, ?it/s]
Downloading (…)of-00002.safetensors:  79%|█████████████████████████████████████████████████████████████████████▏                  | 7.83G/9.96G [20:45<05:50, 6.07MB/s]

**Comment by Zuellni** [comment]
The above are just standard warnings as far as I can tell, but what exactly do you mean by
>it doesn't make a sharp image

Any workflow and/or image examples?
