### ISSUE TITLE
the custom nodes will not show up in the add nodes list, no error message

### ISSUE THREAD

**Issue by vstalingrady** [Zuellni/ComfyUI-Custom-Nodes#8]
vast.ai rented gpu instance on this docker image: runpod/stable-diffusion:comfy-2.1.0
I've installed everything in the right directory at /workspace/ComfyUI/custom_nodes/Zuellni
what's weird is that other custom nodes work with no problems (e.g efficiency nodes)

been trying to figure this out for probably an entire day now, pls help 😭

**Comment by vstalingrady** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'python'

Cannot import /home/user/Downloads/ComfyUI/custom_nodes/Zuellni module for custom nodes: {Errno 2] No such file or directory 'python'

Import times for custom nodes:
 0.0 seconds (IMPORT FAILED): /home/user/Downloads/ComfyUI/custom_nodes/Zuellni
 
found the error message

**Comment by vstalingrady** [comment]
@Zuellni sorry for the bother, this is quite urgent for me. I really appreciate your help

**Comment by Zuellni** [comment]
Cloud issues are above my pay grade but if a config file gets created then try installing requirements manually (as per the readme). If there's no config file after starting the ui, create one yourself in the extension dir:

`config.json`
```json
{
	"Settings": {
		"Install Requirements": false,
		"Update Repository": false,
		"Quiet Update": true
	},
	"Load Nodes": {
		"Aesthetic": true,
		"IF": true,
		"Image": true,
		"Multi": true,
		"Text": true
	}
}
```
If you don't want to use IF nodes, set them to `false` above, you shouldn't have to install anything in that case. I think I'll remove the whole automatic installation since it seems to be causing issues.
